server:
  port: <port>

spring:
  application:
    name: messaging-app
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: <client-id>
            client-secret: <client-secret>
  data:
    cassandra:
      keyspace-name: <keyspace-name>
      username: <username>
      password: <password>
      schema-action: recreate-drop-unused
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

astra-db:
  id: <id>
  region: <region>
  keyspace: <keyspace-name>
  application.token: <token>

datastax.astra:
  secure-connect-bundle: secure-connect-inbox-app.zip